### ISSUE TITLE
每次vite serve都会执行`Pre-bundling`行为吗？

### ISSUE THREAD

**Issue by Beiluola** [electron-vite/vite-plugin-electron-renderer#15]
你好！我在`README.md`中看到：

> When you run vite for the first time, you may notice this message: Pre-bundling: serialport

我理解为类似vite的预构建行为，只有在依赖发生变更时才会再次提示预构建。但是实际上，每次`vite serve`启动，都会输出此提示`Pre-bundling: serialport`，不清楚是文档有误，还是实现有误，或者是我使用有误？

**Comment by caoxiemeihao** [comment]
目前没有缓存功能，每当 `vite serve` 执行，或者 Vite dev server 重启都会导致预构建重新执行。
TODO: 考虑加入缓存计算

**Comment by caoxiemeihao** [comment]
`v0.11.4` 已支持 Pre-Bundling 缓存
