### ISSUE TITLE
wrong esbuild peerDependency

### ISSUE THREAD

**Issue by ZFail** [electron-vite/vite-plugin-electron-renderer#16]
why package have esbuild in peerDependency?
esbuild is in dependencies of vite package
this peerDependency emit warning in my project:
```vite-plugin-electron-renderer@0.11.3" has unmet peer dependency "esbuild@*".```
but i don't want to specify esbuild version in my package.json, i'm already have vite in package.json
maybe replace esbuild peerDependency with vite?

**Comment by caoxiemeihao** [comment]
Are you using pnpm?
