### ISSUE TITLE
Wrong script path

### ISSUE THREAD

**Issue by lexxa-tech** [electron-vite/vite-plugin-electron-renderer#18]
I use electron-vite-react boilerplate, but when i run npm run dev, there is an error in console.

looks like it was an error caused by wrong file extension (it must be preload/index.js not preload/index.ts)

![image](https://user-images.githubusercontent.com/68645489/209605826-75a7e3a7-6be6-4ba8-b5aa-7dc8fcf8a519.png)

**Comment by caoxiemeihao** [comment]
Electron can not support `.ts` file.

**Comment by lexxa-tech** [comment]
so how to change the path from dist electrron/preload/index.ts to electrron/preload/index.js

**Comment by caoxiemeihao** [comment]
<img width="491" alt="image" src="https://user-images.githubusercontent.com/26263658/209608565-832dfedc-efff-4761-8c01-8d7a6dd5a3a5.png">
What's wrong with that?
