### ISSUE TITLE
from v0.11.3 update to v0.12.0, export error: "Uncaught TypeError: cwd is not a function, at node-api.ts", use electron-vite-vue template

### ISSUE THREAD

**Issue by luvletterldl** [electron-vite/vite-plugin-electron-renderer#27]
<img width="611" alt="image" src="https://user-images.githubusercontent.com/26115291/217771058-4892a6f9-d403-411c-87d9-b999a43e3653.png">

{
    "node": "18.12.1",
    "v8": "11.0.226.13-electron.0",
    "uv": "1.43.0",
    "zlib": "1.2.13",
    "brotli": "1.0.9",
    "ares": "1.18.1",
    "modules": "113",
    "nghttp2": "1.47.0",
    "napi": "8",
    "llhttp": "6.0.10",
    "openssl": "1.1.1",
    "cldr": "42.0",
    "icu": "72.1",
    "tz": "2022f",
    "unicode": "15.0",
    "electron": "23.0.0",
    "chrome": "110.0.5481.77"
}

**Comment by caoxiemeihao** [comment]
`v0.12.1` is out.
