### ISSUE TITLE
`buffer.hasOwnProperty()` throws an error

### ISSUE THREAD

**Issue by astoilkov** [electron-vite/vite-plugin-electron-renderer#30]
Let's look at this example from `safer-buffer` package:
```ts
'use strict'

var buffer = require('buffer')
var Buffer = buffer.Buffer

var safer = {}

var key

for (key in buffer) {
  if (!buffer.hasOwnProperty(key)) continue // it throws here
  if (key === 'SlowBuffer' || key === 'Buffer') continue
  safer[key] = buffer[key]
}
```

The call to `hasOwnProperty()` throws.

This is because the `buffer` module is provided as:
```ts
const _M_ = require("buffer");
export const Blob = _M_.Blob;
export const Buffer = _M_.Buffer;
export const File = _M_.File;
export const INSPECT_MAX_BYTES = _M_.INSPECT_MAX_BYTES;
export const SlowBuffer = _M_.SlowBuffer;
export const atob = _M_.atob;
export const btoa = _M_.btoa;
export const constants = _M_.constants;
const keyword_default = _M_.default || _M_;
export const kMaxLength = _M_.kMaxLength;
export const kStringMaxLength = _M_.kStringMaxLength;
export const resolveObjectURL = _M_.resolveObjectURL;
export const transcode = _M_.transcode;
export {
  keyword_default as default,
};
```

**Comment by caoxiemeihao** [comment]
`hasOwnProperty` comes from the prototype chain. 👀
The ESM format only exports the members of the buffer itself. 😅

**Comment by astoilkov** [comment]
I see three ways in which this could work.

1. `import m from` instead of `import * as m from`:
```ts
// now
import * as m from "/@fs/Users/astoilkov/Repos/nota/node_modules/vite-plugin-electron-renderer/builtins/buffer.js?v=59e8e528";

// idea
import m from "/@fs/Users/astoilkov/Repos/nota/node_modules/vite-plugin-electron-renderer/builtins/buffer.js?v=59e8e528";
```

2. Export all prototype methods as well

3. Use `optimizeDeps` as this is a CJS module

**Comment by astoilkov** [comment]
Ok, got it. Do I understand correctly that there isn't anything that can be done to fix this issue inside of the `vite-plugin-electron-renderer` itself?

If yes, feel free to close the issue.

**Comment by caoxiemeihao** [comment]
Maybe we can try to bridge to a new Object 🤔

```js
const _M_fs = require("buffer");

const _M_ = Object.assign({ __esModule: true }, _M_fs);

export const Buffer = _M_.Buffer;
// ...
const keyword_default = _M_.default || _M_;
export {
  keyword_default as default,
};
```

**Comment by astoilkov** [comment]
Aha, yes. I didn't think of that. I like that idea. I think I've seen this kind of output somewhere. Have you tested this?

Sorry for the late response. 😞

**Comment by caoxiemeihao** [comment]
Hey! My bro!
I tried it base on `0.14.0` on my local machine and works! So you try to upgread to `0.1.4.0`, if have something else you can provide a minimal reproduction repo, I will try to resolve it 🐞

**Comment by astoilkov** [comment]
I've upgraded to the latest version and it now works. Thanks!

Closing this issue.
