### ISSUE TITLE
The multi-entry vite application with embedded iframe reports that require is not defined

### ISSUE THREAD

**Issue by SKT1yang** [electron-vite/vite-plugin-electron-renderer#31]
The multi-entry vite application with embedded iframe reports that require is not defined, which should be caused by the insertion of vite-plugin-electron-renderer into external
![9b516cb265cee94c872a883e3d87a2dd](https://user-images.githubusercontent.com/34095649/224608125-3a036332-fef2-4913-9648-d929f9797ca3.png)
![80dfaf1732f773418d4898702804296a](https://user-images.githubusercontent.com/34095649/224608142-382bb465-2cbc-4b29-81d1-0cf3b8ef7981.png)

**Comment by SKT1yang** [comment]
我确认正确配置了，没有iframe是没有任何问题的，也是正常注入的，但是用了iframe后，iframe加载的html就没有node api环境；我可以整一个复现环境，能帮忙看下么

**Comment by SKT1yang** [comment]
iframe加载的html的html我不知道怎么使用nodeIntegration

**Comment by SKT1yang** [comment]
> Ensure the `nodeIntegration` option is set correctly in yourt project. https://github.com/electron-vite/vite-plugin-electron/blob/036e52cf1d5f21d850673690694a07cb8743d674/examples/multiple-window/electron/main.ts#L20

**Comment by caoxiemeihao** [comment]
`nodeIntegrationInSubFrames: true`
