### ISSUE TITLE
v0.12.1 -> v0.13.3 migration guide?

### ISSUE THREAD

**Issue by mtdvlpr** [electron-vite/vite-plugin-electron-renderer#39]
Hi, v12.1 was working perfectly with the following config:
```javascript
{
  nodeIntegration: true,
  optimizeDeps: {
    include: ['fs-extra', 'obs-websocket-js', 'upath'],
  },
}
```

When I try upgrading to v0.13.3 there's a bunch of errors. How would I correctly migrate to the latest version?

**Comment by caoxiemeihao** [comment]
The `v0.13.x` is easy to use the `v0.12.x`, the latest version is `v0.13.14` :)

```diff
{
  nodeIntegration: true,
- optimizeDeps: {
-   include: ['fs-extra', 'obs-websocket-js', 'upath'],
- },
}
```

**Comment by caoxiemeihao** [comment]
Looks like from React rather than Vite.

**Comment by caoxiemeihao** [comment]
Sorry! upgrade to `v0.13.6` to resolve it!
