### ISSUE TITLE
Errors since upgrading to 0.13.7

### ISSUE THREAD

**Issue by Jazcash** [electron-vite/vite-plugin-electron-renderer#46]
![image](https://user-images.githubusercontent.com/1434248/227748381-0501f7e6-5771-4dda-ad9e-57426f7fcaa4.png)

```
00:13:40 [vite] error while updating dependencies:
Error: Build failed with 3 errors:
error: The entry point "http" cannot be marked as external
error: The entry point "https" cannot be marked as external
error: The entry point "stream" cannot be marked as external
    at failureErrorWithLog (C:\Users\jaspe\Repos\bar-lobby\node_modules\vite\node_modules\esbuild\lib\main.js:1636:15)
```

My full vite config and project: https://github.com/beyond-all-reason/bar-lobby/blob/vite-plugin-electron-renderer-update/electron.vite.config.ts#L64

**Comment by Jazcash** [comment]
Some more info:
![image](https://user-images.githubusercontent.com/1434248/227748832-49f11700-a2b8-4218-935e-5720090fb9e6.png)

Btw this only happens when updating from `0.11.4` to `0.13.`. I tried updating other packages such as `vite` and `vite-plugin-electron` but same error.

**Comment by caoxiemeihao** [comment]
Upgrade to `v0.13.8` try to resolve it.

**Comment by Jazcash** [comment]
> Upgrade to `v0.13.8` try to resolve it.

Now I get some new errors

![image](https://user-images.githubusercontent.com/1434248/227770881-fba5f740-5d13-4908-be8c-e98138453d7f.png)

**Comment by caoxiemeihao** [comment]
Upgrade to `v0.13.9`.

**Comment by Jazcash** [comment]
Now it's back to the old error

![image](https://user-images.githubusercontent.com/1434248/227781796-7b6c1956-57bf-45c8-9d94-c54f092b87cf.png)

Sorry 😅

**Comment by caoxiemeihao** [comment]
alex88 的那个 electron-vite npm 包没提供渲染进程解决方案？抄都不抄个完整的？
