### ISSUE TITLE
Deprecation warning since 0.14.0

### ISSUE THREAD

**Issue by fs86** [electron-vite/vite-plugin-electron-renderer#59]
Since using version 0.14.0 I get a deprecation warning:
```
(node:17084) [DEP0091] DeprecationWarning: crypto.DEFAULT_ENCODING is deprecated.
(Use `electron --trace-deprecation ...` to show where the warning was created)
```

**Comment by caoxiemeihao** [comment]
Can you provide a minimal reproduction repo?

**Comment by fs86** [comment]
Hm... I can't reproduce the problem in my demo project. So I guess it must be a conflict between vite-plugin-electron-renderer and another package I use.
