### ISSUE TITLE
0.14.1正常，0.14.2报错

### ISSUE THREAD

**Issue by HaoAu3** [electron-vite/vite-plugin-electron-renderer#65]
具体是electron-log这个依赖导致的

**Comment by HaoAu3** [comment]
renderer({
        resolve: {
          'electron-log': { type: 'cjs' }
        }
      })

**Comment by HaoAu3** [comment]
早上测试了，发现0.14.2不报错了。不清楚是不是0.14.2的依赖升级了。

**Comment by HaoAu3** [comment]
我昨天的操作是，升级全部依赖，清包然后装包，结果运行dev报错。
接着我把vite-plugin-electron-renderer版本从0.14.2定在0.14.1，清包然后装包，运行dev就成功。
 
今天升级全部依赖，清包然后装包，运行dev成功了。
打扰草鞋大大了，不好意思。

**Comment by HaoAu3** [comment]
查看了vite-plugin-electron-renderer的依赖，发现只有rollup的更新显示是“一天前”，
我猜测，前一个版本的rollup只能用于render的0.14.1版本，用于0.14.2会报错。
而新的当前版本的rollup则render的0.14.1和0.14.2版本都正常。

**Comment by caoxiemeihao** [comment]
OK 的，冈巴叠呦
