### ISSUE TITLE
`install.js` is missing

### ISSUE THREAD

**Issue by staniel359** [electron-vite/vite-plugin-electron-renderer#66]
Hello.
Version `0.14.2` is missing `install.js` file.
Is there another way to build Electron files?

**Comment by caoxiemeihao** [comment]
`v0.14.x` dependent `alias.customResolver` to generate the Electron files.

https://github.com/electron-vite/vite-plugin-electron-renderer/blob/v0.14.2/src/index.ts#L148-L153

**Comment by staniel359** [comment]
@caoxiemeihao So if I want to run the build manually (for GitHub Actions), what should I do?

**Comment by staniel359** [comment]
@caoxiemeihao I did it like [this](https://github.com/staniel359/muffon/blob/main/.github/workflows/main.yml#L53).
How could it be done now?

**Comment by caoxiemeihao** [comment]
Just run `vite build` command. the Electron files still will be generated during build time.

**Comment by staniel359** [comment]
@caoxiemeihao Good, thank you!

Also, according to [semver](https://semver.org/#summary), if you make breaking changes, e.g. removing `install.js`, you should change version's first number.
