### ISSUE TITLE
生成的加载路径有误，导致模块无法正常加载，mac正常，windows11下不行

### ISSUE THREAD

**Issue by aimeiyijia** [electron-vite/vite-plugin-electron-renderer#67]
const avoid_parse_require = require; const _M_ = avoid_parse_require("../C:\Users\DELL\Desktop\桌面应用\zmgj\node_modules\.vite-electron-renderer\fs-extra.cjs");

**Comment by caoxiemeihao** [comment]
确实是个 BUG ... 坑爹的 Window💩 ▄█▀█●

**Comment by aimeiyijia** [comment]
> 确实是个 BUG ... 坑爹的 Window💩 ▄█▀█●
先用require了

**Comment by aimeiyijia** [comment]
> 确实是个 BUG ... 坑爹的 Window💩 ▄█▀█●

什么时候修复啊

**Comment by caoxiemeihao** [comment]
看吧
