### ISSUE TITLE
How to work with ws package?

### ISSUE THREAD

**Issue by GeoffreyChen777** [electron-vite/vite-plugin-electron-renderer#70]
Hi, thanks for your work!

I'm trying to use websocket package `ws` https://github.com/websockets/ws with this repo. However, I tried:

```
 ws: {type: "esm"} and ws: {type: "cjs"}
```

none of them work.

```
Uncaught TypeError: browser.WebSocketServer is not a constructor
```

Could you please help me with that?

For a simple demo, just add:

```
import { WebSocketServer } from "ws";

const wss = new WebSocketServer({ port: 8080 });
console.log("ws", wss, WebSocketServer);

```

in the quick-start demo.

Thanks!

**Comment by caoxiemeihao** [comment]
See here 👉 https://github.com/electron-vite/vite-plugin-electron/blob/v0.11.2/src/config.ts#L56-L66

**Comment by GeoffreyChen777** [comment]
Thanks!

**Comment by zbouslikhin** [comment]
I have exactly the same issue; trying to use ws, but I get Uncaught TypeError: Class extends value #<Object> is not a constructor or null



> Perhaps you can try to config following. See here 👉 https://github.com/electron-vite/vite-plugin-electron/blob/v0.11.2/src/config.ts#L56-L66

I tried this solution, no success. 
My vite.config is as follows:
```
// vite.config.ts
import { defineConfig } from 'vite';
import { resolve } from 'path';
import react from '@vitejs/plugin-react';
import renderer from 'vite-plugin-electron-renderer';

export default defineConfig({
  resolve: {
    mainFields: ['module', 'jsnext:main', 'jsnext'],
    alias: {
      '@': resolve(__dirname, './src'),
    },
  },

  plugins: [
    react(),
    renderer(),
  ],
});
```

Any idea would be much appreciated!
