### ISSUE TITLE
Use Pixi.js failed

### ISSUE THREAD

**Issue by chenyuyu118** [electron-vite/vite-plugin-electron-renderer#77]
console error log:
caught Error: Dynamic require of "url" is not supported
    at chunk-AUZ3RYOM.js?v=c11b5bbd:12:9
    at url.mjs:1:50

```
url.mjs
const avoid_parse_require = require; const _M_ = avoid_parse_require("url");
export const Url = _M_.Url;
export const parse = _M_.parse;
export const resolve = _M_.resolve;
export const resolveObject = _M_.resolveObject;
export const format = _M_.format;
export const URL = _M_.URL;
export const URLSearchParams = _M_.URLSearchParams;
export const domainToASCII = _M_.domainToASCII;
export const domainToUnicode = _M_.domainToUnicode;
export const pathToFileURL = _M_.pathToFileURL;
export const fileURLToPath = _M_.fileURLToPath;
export const urlToHttpOptions = _M_.urlToHttpOptions;
const keyword_default = _M_.default || _M_;
export {
  keyword_default as default,
};
```

I'm trying to import pixi.js like bellow:
```js
import {Application, Text} from 'pixi.js'
```

**Comment by caoxiemeihao** [comment]
I used `pixi.js` in[ electron-vite-vue](https://github.com/electron-vite/electron-vite-vue) works fine :)

<img width="700" alt="image" src="https://github.com/electron-vite/vite-plugin-electron-renderer/assets/26263658/ef116526-e36e-407f-9180-ae54d5bcdea1">

**Comment by chenyuyu118** [comment]
> Reference in n

I update my BrowserWindow args, use 
``` 
    nodeIntegration: true,
    contextIsolation: false
```
Then it work, but the api I defined by contextBridge dones't work now.

**Comment by caoxiemeihao** [comment]
Can you provide a minimal reproduction repo?

**Comment by chenyuyu118** [comment]
> Can you provide a minimal reproduction repo?

Like this? https://github.com/chenyuyu118/electron-vite-vue-pixijs.git

**Comment by oliverschwendener** [comment]
I am experiencing the same issue since upgrading vite from 5.1.5 to 5.2.8. I created a repo here to reproduce the issue: https://github.com/oliverschwendener/vitest-bug.

Did I misconfigure something, or is this actually a bug?
