### ISSUE TITLE
A code error occurred during the vitest unit test.

### ISSUE THREAD

**Issue by maogecarry** [electron-vite/vite-plugin-electron-renderer#78]
![image](https://github.com/electron-vite/vite-plugin-electron-renderer/assets/46319720/6c641111-a48c-4a01-86c0-fa5578a408f0)
devDependencies：
    "vite": "^4.4.6",
    "vite-plugin-electron": "^0.12.0",
    "vite-plugin-electron-renderer": "^0.14.5",
    "vite-plugin-svg-icons": "^2.0.1",
    "vitest": "^0.34.4",
    "vue-tsc": "^1.8.6"

**Comment by wethil** [comment]
I have same problem, did you find a solution @maogecarry ?

**Comment by maogecarry** [comment]
> I have same problem, did you find a solution @maogecarry ?

not yet

**Comment by maogecarry** [comment]
solved by #77  @wethil

**Comment by wethil** [comment]
thanks! @maogecarry

**Comment by oliverschwendener** [comment]
I am experiencing a similar issue since upgrading vite from 5.1.7 to 5.2.0. I created a repo here to reproduce the issue: https://github.com/oliverschwendener/vitest-bug.

Did I misconfigure something, or is this actually a bug?

**Comment by caoxiemeihao** [comment]
@oliverschwendener I tried running the repo you provided and did not find any errors.

**Comment by oliverschwendener** [comment]
The error also occurs on when running the tests on GitHub Actions, see here: https://github.com/oliverschwendener/vitest-bug/actions/runs/8601332372/job/23568347598

**Comment by caoxiemeihao** [comment]
`vitest` runs in the `node.js` environment, while the code polyfill in with `vite-plugin-electron-renderer` can only run in the Electron renderer process environment, so running `npm run test` will cause errors.

**Comment by oliverschwendener** [comment]
Thanks! I didn't realize that I could remove the `renderer()` plugin when running the tests 🤦 . This solves my problem, thanks for helping out!
