### ISSUE TITLE
使用 mqtt 库，开发环境下有警告并且加载缓慢，打包后报错，请问如何解决。

### ISSUE THREAD

**Issue by xudongdong40** [electron-vite/vite-plugin-electron-renderer#80]
# 版本与安装方式
"mqtt": "^4.3.7",
"vite-plugin-electron": "^0.14.0",
"vite-plugin-electron-renderer": "^0.14.5"

cnpm 安装

```js
// vite.config.json
renderer: {
  resolve: {
    mqtt: { type: 'cjs' }
  }
}
```

# dev模式下
<img width="1696" alt="iShot_2023-12-25_09 59 18" src="https://github.com/electron-vite/vite-plugin-electron-renderer/assets/44309218/8389d439-7ad8-4fd0-b50b-fa9430a00922">

# 打包后
可执行 `cnpm run build` 正常打包，但是有错误。
<img width="798" alt="image" src="https://github.com/electron-vite/vite-plugin-electron-renderer/assets/44309218/adf0b34c-4b3d-4e51-8720-ba207807312c">
已经试过根据提示安装对应包，最后提示`Cannot find module 'process/'`
故认为此种非正确解决方式。

请问如何解决。
谢谢。

**Comment by xudongdong40** [comment]
补充：dev模式下，页面可以正常加载，并且功能可以正常使用。加载速度很慢。

**Comment by caoxiemeihao** [comment]
我不知道 `mqtt` 是不是纯前端库，如果是的话就不要 `resolve` 配置加载它了，Vite 可以正确的构建它。
要是感觉性能还是不行，你可能需要考虑是否放到主进程运行效果更好一些

**Comment by xudongdong40** [comment]
> 我不知道 `mqtt` 是不是纯前端库，如果是的话就不要 `resolve` 配置加载它了，Vite 可以正确的构建它。 要是感觉性能还是不行，你可能需要考虑是否放到主进程运行效果更好一些

不是。因为有 Buffer 之类的，是个后端库。确实关了 rander 以后走 ipc 性能更好。就是有点不方便。
