### ISSUE TITLE
render这个插件到底是什么

### ISSUE THREAD

**Issue by iiiSnow** [electron-vite/vite-plugin-electron-renderer#81]
我需要打开两个窗口，窗口的内容都是vue+vite写的。需要配置这个render插件以及multi-window插件吗，实在是没看出来作用是啥，前端小白。另外这么好的项目，建议增加中文说明，普及度能高一些。

**Comment by xudongdong40** [comment]
render插件让浏览器侧可以调用 node 侧的api。包括解析 node 侧的一些包。不然的话你就需要同过 ipc 通信解决。

**Comment by iiiSnow** [comment]
> render插件让浏览器侧可以调用 node 侧的api。包括解析 node 侧的一些包。不然的话你就需要同过 ipc 通信解决。

那不是preload干的事么，我的项目vue页面跟electron要进行频繁通信，现在ipc都写preload里。可能有别的用法吧

**Comment by xudongdong40** [comment]
> > render插件让浏览器侧可以调用 node 侧的api。包括解析 node 侧的一些包。不然的话你就需要同过 ipc 通信解决。
> 
> 那不是preload干的事么，我的项目vue页面跟electron要进行频繁通信，现在ipc都写preload里。可能有别的用法吧

使用 render 以后就不再用ipc通信了。写起来会方便些。
