### ISSUE TITLE
无法pnpm install成功

### ISSUE THREAD

**Issue by liuhean** [electron-vite/vite-plugin-electron-renderer#84]

**Comment by liuhean** [comment]
提错仓库了，不好意思

**Comment by caoxiemeihao** [comment]
配置下 `.npmrc` 文件
<img width="1095" alt="image" src="https://github.com/electron-vite/vite-plugin-electron-renderer/assets/26263658/2d4355b2-29e9-48af-9092-42ed55cfc308">
